In [2]:
import numpy as np

grid_size = 5
num_states = 25
actions = ["up", "down", "left", "right"]
num_actions = 4

rewards = np.full(num_states, -1)
rewards[24] = 100

q_table = np.zeros((num_states, num_actions))

def take_action(state, action):
    row = state // 5
    col = state % 5

    if action == 0:
        row = max(0, row - 1)
    elif action == 1:
        row = min(4, row + 1)
    elif action == 2:
        col = max(0, col - 1)
    elif action == 3:
        col = min(4, col + 1)

    return row * 5 + col

learning_rate = 0.1
discount = 0.9
epsilon = 0.2

for episode in range(500):

    state = np.random.randint(0, 25)

    while state != 24:

        if np.random.rand() < epsilon:
            action = np.random.randint(0, 4)
        else:
            action = np.argmax(q_table[state])

        next_state = take_action(state, action)

        best_future = np.max(q_table[next_state])

        q_table[state, action] = q_table[state, action] + \
            learning_rate * (rewards[next_state] + discount * best_future - q_table[state, action])

        state = next_state

print("Q-Table:\n", q_table)

best_actions = np.argmax(q_table, axis=1)
policy = np.array([actions[a] for a in best_actions])
print("\nOptimal Policy:\n", policy.reshape(5,5))

Q-Table:
 [[-9.43819161e-01  1.72043878e+01 -1.03225851e+00 -9.39422087e-01]
 [ 5.61083163e+00  4.15049827e+01  2.26920171e-01  7.34839793e-01]
 [-7.69359882e-01  3.44733202e+01  1.16425106e+00  1.80133595e+00]
 [-5.85198506e-01  5.10238373e+01 -5.86721911e-01  7.30623190e+00]
 [-4.81366810e-01  5.85134234e+01 -4.09392640e-01 -3.94039900e-01]
 [-8.58300678e-01  1.14405595e+01 -7.04943295e-01  4.36785179e+01]
 [ 4.67332062e+00  5.48807122e+01  5.86746436e+00  8.10656897e+00]
 [ 4.38688407e+00  6.02903598e+01  1.78880617e+01  2.05059683e+01]
 [ 7.70411230e+00  6.98426373e+01  4.88133663e+00  1.19719214e+01]
 [ 6.94915094e+00  7.90004045e+01  1.42018000e+01  1.29711009e+01]
 [-4.57221479e-01  1.04352037e+00  1.34644265e+01  5.40973736e+01]
 [ 2.18789543e+01  2.78369244e+01  1.34055013e+01  6.21705762e+01]
 [ 3.27681228e+01  2.92132835e+01  3.82335245e+01  7.01899902e+01]
 [ 4.41479621e+01  4.33959054e+01  4.16496087e+01  7.91000000e+01]
 [ 5.53160646e+01  8.90000000e+01  5.65362133e+01  5